[package]
name = "mcf"
version = "0.17.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true

[profile.dev]
opt-level = 0

[dependencies]
clap = { version = "3.2.25", features = ["derive"] }
clap_complete = "3.2.5"
dirs = "4.0.0"
anyhow = "1.0.75"
log = "0.4.0"
env_logger = "0.9.0"
prettytable-rs = "0.10.0"
lib = { path = "../lib" }
tokio = { version = "1", features = ["full"] }