[package]
name = "integration"
version = "0.17.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcf = { path = "../cli" }
assert_cmd = "2.0.11"

[features]
integration = []