name: ci-tags

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-workflow-rust-cache:
    name: run rust-cache action
    uses: mdpadberg/multi-cf/.github/workflows/rust-cache.yml@main
  call-workflow-clippy:
    name: run clippy github action
    needs: [call-workflow-rust-cache]
    uses: mdpadberg/multi-cf/.github/workflows/clippy.yml@main
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-unit-tests:
    name: run unit tests
    needs: [call-workflow-clippy]
    uses: mdpadberg/multi-cf/.github/workflows/unit-tests.yml@main
  call-workflow-integration-tests:
    name: run integration tests
    needs: [call-workflow-clippy]
    uses: mdpadberg/multi-cf/.github/workflows/integration-tests.yml@main   
  call-workflow-version-bump:
    name: run version bump
    permissions:
      contents: write
    needs: [call-workflow-unit-tests, call-workflow-integration-tests]
    uses: mdpadberg/multi-cf/.github/workflows/version-bump.yml@main 
    with:
      release-version: ${GITHUB_REF#refs/*/}
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}  
  call-workflow-create-release:
    name: run create release
    permissions:
      contents: write
    needs: [call-workflow-version-bump]
    uses: mdpadberg/multi-cf/.github/workflows/create-release.yml@main 
    with:
      release-version: ${GITHUB_REF#refs/*/}
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-build-release:
    name: run build release
    permissions:
      contents: write
    needs: [call-workflow-create-release]
    uses: mdpadberg/multi-cf/.github/workflows/build-release.yml@main 
    with:
      release-version: ${GITHUB_REF#refs/*/}
      binary-name: multi-cf
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
  trigger_homebrew_tap:
    name: Trigger homebrew-tap
    needs: [build_release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'mdpadberg',
            repo: 'homebrew-tap',
            workflow_id: 'create-mcf-rb.yml',
            ref: 'main'
          })
  trigger_scoop_bucket:
    name: Trigger scoop-bucket
    needs: [build_release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'mdpadberg',
            repo: 'scoop-bucket',
            workflow_id: 'create-mcf-json.yml',
            ref: 'main'
          })
