name: run clippy github action

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
  
jobs:
  clippy:
    name: run clippy github action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Install Rust with cargo
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ubuntu-latest-x86_64-unknown-linux-gnu
    - uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}