name: run integration tests

on:
  workflow_call:

jobs:
  integration-tests:
    name: run integration tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install Rust with cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - name: Run integration tests
        run: docker compose up --exit-code-from mcf --build