name: run rust-cache action

on:
  workflow_call:

jobs:
  rust-cache:
    name: run rust-cache action
    strategy:
      matrix:
        include:
        - os: macos-latest
          rust-target: x86_64-apple-darwin
        - os: ubuntu-latest
          rust-target: x86_64-unknown-linux-gnu
        - os: windows-latest
          rust-target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Rust with cargo
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ matrix.os }}-${{ matrix.rust-target }}